export const CATEGORIES = [
  { id: 'preseed', label: 'Pre-Seed VC', color: '#ED7C25', emoji: '🚀' },
  { id: 'nondilutive', label: 'Non-Dilutive (US)', color: '#22c55e', emoji: '🏛️' },
  { id: 'fellowships', label: 'Fellowships', color: '#818cf8', emoji: '🎓' },
  { id: 'awards', label: 'Awards & Nominations', color: '#f472b6', emoji: '🏅' },
  { id: 'competitions', label: 'Prizes & Competitions', color: '#F3AC41', emoji: '🏆' },
  { id: 'india', label: 'India Track (INSPIN)', color: '#fb923c', emoji: '🇮🇳' },
  { id: 'canada', label: 'Canada Track', color: '#ef4444', emoji: '🍁' },
  { id: 'global', label: 'Global Prizes', color: '#c084fc', emoji: '🌍' },
  { id: 'expertwitness', label: 'Expert Witness', color: '#a78bfa', emoji: '⚖️' },
  { id: 'consulting', label: 'Expert Networks', color: '#38bdf8', emoji: '💡' },
];

export const OPPORTUNITIES = [

  // ── PRE-SEED VC
  { id:'starburst', category:'preseed', name:'Starburst Ventures', amount:'Up to $1M', status:'todo', priority:1, warmIntro:false, deadline:'Rolling', action:'Send deck to pitch@starburst.vc — no warm intro. Subject: Pre-Seed | MSS | Propulsion and Orbital Maneuver. Pitch MSS not II LLC.', deepResearchPrompt:'Research Starburst Ventures 2026. Fund size, recent investments, submission policy, portfolio in space propulsion, ITAR stance. Competing A&D pre-seed funds accepting cold pitches.', notes:'Morpheus Space and Outpost are closest analogs. Natalya Bailey probes propulsion physics. Jacqueline Tame probes ITAR. File one provisional patent before pitching.', url:'https://www.starburst.vc', entity:'MSS' },
  { id:'boost', category:'preseed', name:'Boost.vc', amount:'$500K', status:'todo', priority:2, warmIntro:false, deadline:'Rolling', action:'Apply via boost.vc. Deep tech, no warm intro.', deepResearchPrompt:'Research Boost.vc 2026. Application process, batch schedule, portfolio in aerospace/defense/robotics.', notes:'Good fallback alongside Starburst.', url:'https://www.boost.vc', entity:'MSS or II LLC' },
  { id:'shieldcapital', category:'preseed', name:'Shield Capital', amount:'Seed+', status:'todo', priority:3, warmIntro:false, deadline:'Rolling', action:'Apply via shieldcap.com. Former military GPs. Defense and national security.', deepResearchPrompt:'Research Shield Capital 2026. Fund size, check range, portfolio, GP backgrounds, cold outreach policy.', notes:'Best for Inspired Defense vehicle once incorporated.', url:'https://shieldcap.com', entity:'Inspired Defense (to be formed)' },
  { id:'lockheedventures', category:'preseed', name:'Lockheed Martin Ventures', amount:'Variable', status:'todo', priority:4, warmIntro:false, deadline:'Rolling', action:'Submit via lockheedmartin.com/ventures.', deepResearchPrompt:'Research Lockheed Martin Ventures 2026. Investment thesis, check size, cold submission process.', notes:'Strategic: pilot customers and acquisition pathway.', url:'https://www.lockheedmartin.com/en-us/who-we-are/lockheed-martin-ventures.html', entity:'MSS or II LLC' },
  { id:'inqtel', category:'preseed', name:'In-Q-Tel (CIA Venture Fund)', amount:'Variable', status:'todo', priority:5, warmIntro:false, deadline:'Rolling', action:'Submit via iqt.org/submit-your-technology. UDC dual-use autonomy angle.', deepResearchPrompt:'Research In-Q-Tel 2026. Investment thesis, technology areas, whether solo founder LLC is competitive.', notes:'CIA-backed. Very patient capital, long evaluation.', url:'https://www.iqt.org', entity:'II LLC' },

  // ── NON-DILUTIVE (US)
  { id:'sam-validation', category:'nondilutive', name:'SAM.gov Validation — BLOCKS EVERYTHING', amount:'Unlocks all federal funding', status:'inprogress', priority:1, warmIntro:false, deadline:'ASAP — do this today', action:'Check UEI D4YUPMXSEKJ5 at sam.gov. One notarization step outstanding. Complete it. Blocks every SBIR, DOE, DARPA, NASA, DIU submission.', deepResearchPrompt:'Research SAM.gov external validation notarization step 2026. What is required, which office, how long, expedite pathway?', notes:'HIGHEST LEVERAGE SINGLE ACTION. Nothing federal moves without this.', url:'https://sam.gov', entity:'MSS' },
  { id:'nsf-sbir', category:'nondilutive', name:'NSF SBIR Phase I — Project Pitch', amount:'$305K → $1.25M Phase II', status:'inprogress', priority:2, warmIntro:false, deadline:'Pitch portal OPEN NOW. Full proposal: July 27, 2026', action:'MSS pitch REV07 nearly done. Shardul fills Q15 (3 partner names) and Q16 (2 advisor names). Submit at seedfund.nsf.gov. Solicitation NSF 26-510.', deepResearchPrompt:'Research NSF SBIR 26-510 2026. Current pitch window, Q13-Q16 requirements, rejection reasons, invitation rate. Research Strategic Breakthrough Awards tier (up to $30M).', notes:'No prior NSF award. No cost share. Strongest topic: Space (SP). BESM fits Power Management under II LLC separately.', url:'https://seedfund.nsf.gov', entity:'MSS (+ II LLC for BESM)' },
  { id:'doe-sbir', category:'nondilutive', name:'DOE SBIR — VTO + AMMTO Topics', amount:'$200K Phase I', status:'todo', priority:3, warmIntro:false, deadline:'Release 3 expected mid-2026', action:'Monitor energy.gov/sbir for Release 3. VTO = electric motors, non-rare-earth magnets. AMMTO = advanced manufacturing, AI for manufacturing. Free Phase 0 assistance for first-timers.', deepResearchPrompt:'Research DOE SBIR 2026 Release 3. Expected opening, VTO and AMMTO topic numbers for rare-earth-free motors, Phase 0 assistance, winning proposal characteristics.', notes:'5/5 topic match for BESM. Apply under II LLC.', url:'https://www.energy.gov/science/sbir', entity:'II LLC' },
  { id:'arpa-e', category:'nondilutive', name:'ARPA-E OPEN Program', amount:'$1M–$10M', status:'todo', priority:4, warmIntro:false, deadline:'Periodic FOAs — register at arpa-e-foa.energy.gov', action:'Register at arpa-e-foa.energy.gov. QESM rare-earth-free motor as disruptive transportation electrification technology.', deepResearchPrompt:'Research ARPA-E OPEN 2026. Next OPEN solicitation expected date, current focused program areas, solo LLC competitiveness, award timeline, recent awardees in electric machines.', notes:'Highest dollar non-dilutive. ~5% success rate. QESM is exactly the transformative energy tech ARPA-E funds.', url:'https://arpa-e.energy.gov', entity:'II LLC' },
  { id:'darpa-baa', category:'nondilutive', name:'DARPA Office-Wide BAA', amount:'$500K–$5M', status:'todo', priority:5, warmIntro:false, deadline:'Rolling — check sam.gov', action:'Submit white paper to current DARPA TTO or I2O BAA. UDC + autonomous systems angle. White paper first.', deepResearchPrompt:'Research open DARPA BAAs 2026 for autonomous systems, control theory, power electronics, space propulsion. White paper format, solo founder competitiveness.', notes:'UDC framework is genuinely DARPA-grade.', url:'https://www.darpa.mil/work-with-us/opportunities', entity:'II LLC or MSS' },
  { id:'doe-sbv', category:'nondilutive', name:'DOE Small Business Vouchers (SBV)', amount:'$50K–$300K + lab access', status:'todo', priority:6, warmIntro:false, deadline:'Periodic — check sbv.org', action:'Apply at sbv.org. Partner with Argonne or Oak Ridge for BESM motor design simulation and testing.', deepResearchPrompt:'Research DOE Small Business Vouchers 2026. Next solicitation, accessible national labs, whether simulation-only work qualifies, timeline to award.', notes:'Unlocks national lab equipment without equity. ORNL and Argonne perfect for BESM.', url:'https://sbv.org', entity:'II LLC' },
  { id:'afwerx', category:'nondilutive', name:'AFWERX Open Topic SBIR', amount:'$75K–$150K', status:'todo', priority:7, warmIntro:false, deadline:'Rolling', action:'Register at afsbirsttr.us. Autonomy or perception topic via PR015 or PR041.', deepResearchPrompt:'Research AFWERX Open Topic SBIR 2026. Open topics, deadlines, funded vs unfunded proposal characteristics.', notes:'Faster turnaround than standard DoD SBIR.', url:'https://afsbirsttr.us', entity:'MSS or II LLC' },
  { id:'diu-cso', category:'nondilutive', name:'DIU Commercial Solutions Opening', amount:'$1M–$5M', status:'todo', priority:8, warmIntro:false, deadline:'Rolling', action:'One-page white paper on autonomous perception or propulsion. Submit at diu.mil.', deepResearchPrompt:'Research DIU CSO 2026. Currently open CSOs, winning white paper characteristics, time to award.', notes:'No prototype required. Fast decision cycle.', url:'https://www.diu.mil/work-with-us/open-solicitations', entity:'MSS or II LLC' },
  { id:'deter-ara', category:'nondilutive', name:'DETER ARA (AFRL Directed Energy)', amount:'Variable', status:'todo', priority:9, warmIntro:false, deadline:'Open through Aug 10, 2027', action:'Submit white paper via SAM.gov. DE source components angle fits PR020 power electronics.', deepResearchPrompt:'Research DETER ARA AFRL 2026. SAM.gov number, white paper template, evaluation criteria, how power electronics fits.', notes:'Long window. Low friction entry.', url:'https://sam.gov', entity:'II LLC' },
  { id:'cloud-credits', category:'nondilutive', name:'Cloud Credits — NVIDIA / AWS / Google / Microsoft', amount:'$100K–$350K each', status:'todo', priority:10, warmIntro:false, deadline:'Rolling — apply all four this week', action:'NVIDIA Inception: inception.nvidia.com | AWS Activate: aws.amazon.com/activate | Google for Startups: cloud.google.com/startup | Microsoft for Startups: microsoft.com/startups', deepResearchPrompt:'Research startup cloud credit programs 2026. What each gives, eligibility, approval time, whether solo LLC gets highest tier.', notes:'Zero equity, zero cost share. $100K-350K compute per program.', url:'https://inception.nvidia.com', entity:'II LLC' },

  // ── FELLOWSHIPS
  { id:'activate', category:'fellowships', name:'Activate Fellowship (Cyclotron Road / LBNL)', amount:'$300K+ over 2 years', status:'todo', priority:1, warmIntro:false, deadline:'~Oct 2026', action:'Apply at activate.org. Position BESM/QESM rare-earth-free motor as the core technology. Solves lab access bottleneck.', deepResearchPrompt:'Research Activate Fellowship 2026. Exact deadline, lab access, stipend, acceptance rate (<5%), recent fellows in motor controls, PR eligibility, additionality criteria.', notes:'5/5 priority. Hardware-forward. Explicitly solves the no-lab constraint. US PR is sufficient.', url:'https://www.activate.org', entity:'II LLC' },
  { id:'innovation-crossroads', category:'fellowships', name:'Innovation Crossroads (ORNL/DOE)', amount:'$350K+ over 2 years', status:'todo', priority:2, warmIntro:false, deadline:'Fall 2026', action:'Apply at innovationcrossroads.ornl.gov. Oak Ridge embedded. Requires relocation to Tennessee. Highest total value fellowship.', deepResearchPrompt:'Research Innovation Crossroads ORNL 2026. Exact deadline, stipend, lab access, IP ownership, past cohort in motor drives or power electronics, relocation requirement details.', notes:'ORNL world-class manufacturing and materials for BESM fabrication. Relocation required.', url:'https://innovationcrossroads.ornl.gov', entity:'II LLC' },
  { id:'chain-reaction', category:'fellowships', name:'Chain Reaction Innovations (Argonne/DOE)', amount:'$300K+ over 2 years', status:'todo', priority:3, warmIntro:false, deadline:'Fall 2026', action:'Apply at chainreaction.anl.gov. Argonne embedded. Chicago area. Manufacturing and energy focus.', deepResearchPrompt:'Research Chain Reaction Innovations 2026. Deadline, Argonne lab access for electric machines, past fellows, PR eligibility.', notes:'Argonne has EV and advanced manufacturing divisions directly relevant to BESM.', url:'https://chainreaction.anl.gov', entity:'II LLC' },
  { id:'breakthrough-energy', category:'fellowships', name:'Breakthrough Energy Fellows (Gates)', amount:'$500K–$3M', status:'todo', priority:4, warmIntro:false, deadline:'~Fall 2026', action:'Apply at breakthroughenergy.org/our-work/fellows. Rare-earth-free motors as critical materials alternative for clean energy. Must show pathway to 500M ton CO2 reduction.', deepResearchPrompt:'Research Breakthrough Energy Fellows 2026. Exact deadline, Innovator vs Business vs Explorer tracks, acceptance rate, past fellows in electric machines or critical materials, whether dilutive SAFE/Note is required.', notes:'Highest dollar fellowship. Critical materials angle maps to energy security thesis. Catalytic funding is dilutive (SAFE).', url:'https://breakthroughenergy.org/our-work/fellows', entity:'II LLC' },
  { id:'west-gate', category:'fellowships', name:'West Gate Fellowship (NREL/DOE)', amount:'$300K+ over 2 years', status:'todo', priority:5, warmIntro:false, deadline:'Spring 2026 — check now', action:'Apply at westgatefellows.org. NREL Golden CO embedded. Renewable energy and transportation focus.', deepResearchPrompt:'Research West Gate Fellowship NREL 2026. Currently open, deadline, NREL lab access for EV motor research, past fellows, PR eligibility.', notes:'NREL has EV and grid research relevant to UTEI and BESM.', url:'https://www.nrel.gov', entity:'II LLC' },

  // ── AWARDS & NOMINATIONS
  { id:'macarthur', category:'awards', name:'MacArthur Fellowship (Genius Grant)', amount:'$800K over 5 years', status:'todo', priority:1, warmIntro:false, deadline:'Nomination only — cannot apply', action:'Build visibility: publish, keynotes, science journalists. Identify nominators in IEEE leadership, MIT network, former Nexteer executives. 225-patent profile plus rare-earth-free work is nomination-worthy.', deepResearchPrompt:'Research MacArthur Fellowship nomination process 2026. Who can nominate, what increases nomination likelihood, engineer/inventor profiles selected in last 5 years, how to increase anonymous nominator visibility.', notes:'Cannot apply. US PR qualifies. One of highest-value awards in existence.', url:'https://www.macfound.org/programs/fellows/', entity:'Prerit individually' },
  { id:'lemelson-mit', category:'awards', name:'Lemelson-MIT Prize', amount:'$500K', status:'todo', priority:2, warmIntro:false, deadline:'Nomination-based — build pipeline now', action:'Contact MIT alumni network and IEEE IAS leadership about nomination. 225+ patents is exceptional and exactly the Lemelson profile.', deepResearchPrompt:'Research Lemelson-MIT Prize 2026. Nomination process, nominator criteria, recent winner patent/invention profiles, solo founder without university affiliation competitiveness.', notes:'225+ patents is the strongest possible Lemelson profile.', url:'https://lemelson.mit.edu/prize', entity:'Prerit individually' },
  { id:'earthshot', category:'awards', name:'Earthshot Prize (Royal Foundation)', amount:'£1M', status:'todo', priority:3, warmIntro:false, deadline:'Via Official Nominator — 2026 ceremony in Mumbai', action:'Find an Official Nominator. Category: Fix Our Climate. Rare-earth-free motors reducing critical material dependence is the angle. 2026 ceremony in Mumbai.', deepResearchPrompt:'Research Earthshot Prize 2026. Official Nominator list, Fix Our Climate category values, US/India dual-presence company eligibility, 2026 ceremony timeline, past winners.', notes:'2026 ceremony in Mumbai. REE-free motors = Fix Our Climate. Strong India angle via INSPIN.', url:'https://earthshotprize.org', entity:'II LLC or INSPIN' },
  { id:'ieee-tesla', category:'awards', name:'IEEE Nikola Tesla Award', amount:'Medal + honorarium', status:'todo', priority:4, warmIntro:false, deadline:'Nomination deadline Jan 15, 2027', action:'Coordinate with IEEE IAS and IEEE PES colleagues to build nomination package. Domain: generation and utilization of electric power. $7B lifetime revenue impact is the headline.', deepResearchPrompt:'Research IEEE Nikola Tesla Award 2026. Nomination process, recent recipients, whether industry researcher outside academia can win, how to build nomination package.', notes:'Perfect domain match. $7B lifetime revenue generated by motor control work. IEEE Senior Member status helps.', url:'https://www.ieee.org/about/awards/ieee-nikola-tesla-award.html', entity:'Prerit individually' },
  { id:'ieee-fellow', category:'awards', name:'IEEE Fellow Elevation', amount:'Highest IEEE designation', status:'todo', priority:5, warmIntro:false, deadline:'Nomination deadline ~Feb 2027 for 2028 class', action:'Assemble nomination committee of existing IEEE Fellows. Apply under Application Engineer/Practitioner or Technical Leader track. Cite economic enhancements from automotive motor control work.', deepResearchPrompt:'Research IEEE Fellow elevation process 2026. Application Engineer track vs Technical Leader track requirements, how many IEEE Fellows are needed to nominate, timeline from nomination to elevation, what citation language works best for industry practitioners.', notes:'Prior IEEE IAS Young Member Award is strong prerequisite signal. Build committee from IAS connections.', url:'https://www.ieee.org/membership/fellows/', entity:'Prerit individually' },
  { id:'nagamori', category:'awards', name:'Nagamori Award (Japan)', amount:'Up to 5M JPY (~$35K)', status:'todo', priority:6, warmIntro:false, deadline:'Application cycle late 2026 — check nagamori-f.or.jp', action:'Prepare English CV and patent/publication dossier. Secure recommendation letter from a motor expert. Apply at nidec.com/nagamori-f. This award is tailor-made for motor experts.', deepResearchPrompt:'Research Nagamori Foundation Award 2026. Exact application deadline, nomination vs self-application, recommendation letter requirements, recent winners and their motor expertise profiles, whether non-Japanese applicants win regularly.', notes:'Tailor-made for motor experts. 225+ patents in motors is a statistically dominant submission. Nidec (motor company) runs this.', url:'https://www.nidec.com/en/nagamori-f/', entity:'Prerit individually' },
  { id:'infosys-prize', category:'awards', name:'Infosys Prize (Engineering & CS)', amount:'$100K USD', status:'todo', priority:7, warmIntro:false, deadline:'Nomination spring 2026 — check now, age cutoff 40', action:'Urgently cultivate relationships with Infosys Science Foundation Nomination Council members. Self-nomination forbidden. Age cutoff is 40 — you are 36 and IN THE WINDOW now. This closes permanently in 4 years.', deepResearchPrompt:'Research Infosys Prize Engineering and CS category 2026. Who sits on the Nomination Council, how to reach them, recent winners and their profiles, exact age cutoff date calculation, nomination submission process and deadline.', notes:'URGENT — age cutoff 40. Indian citizenship qualifies. Autonomous systems and multi-subsystem diagnostics are the angle. Window closes permanently in ~4 years.', url:'https://www.infosysprize.org', entity:'Prerit individually' },
  { id:'wipo-global', category:'awards', name:'WIPO Global Awards', amount:'Platform visibility + mentorship', status:'todo', priority:8, warmIntro:false, deadline:'Spring 2026 — check wipo.int/awards', action:'Draft SME application mapping the 225-patent portfolio commercialization journey. Focus on EV propulsion or energy intelligence. Apply at wipo.int/awards.', deepResearchPrompt:'Research WIPO Global Awards 2026. Application deadline, judging criteria, whether non-cash nature limits value, what platform access and mentorship actually provides, past winners and their IP profiles.', notes:'Non-cash but massive international platform visibility. 225 patents weaponized as IP commercialization story.', url:'https://www.wipo.int/en/web/awards', entity:'II LLC or INSPIN' },
  { id:'zayed-prize', category:'awards', name:'Zayed Sustainability Prize', amount:'Up to $1.2M per category', status:'todo', priority:9, warmIntro:false, deadline:'~June 2026 — check zayedsustainabilityprize.com', action:'Compile operational metrics: projected carbon offsets from rare-earth-free motor adoption, energy efficiency gains from UTEI. Submit corporate application at zayedsustainabilityprize.com. Category: Energy or Climate Action.', deepResearchPrompt:'Research Zayed Sustainability Prize 2026. Exact June 2026 deadline, SME category requirements, what quantifiable environmental metrics are required, past winners in energy or motors, whether a US/India company qualifies.', notes:'$7.2M total prize pool. Energy and climate action categories. Rare-earth-free motors + UTEI = strong fit.', url:'https://zayedsustainabilityprize.com', entity:'II LLC or INSPIN' },
  { id:'cii-ip', category:'awards', name:'CII Industrial IP Awards (India)', amount:'Recognition + visibility', status:'todo', priority:10, warmIntro:false, deadline:'Annual — 2026 cycle ongoing', action:'Apply through INSPIN Private Limited. Self-nomination accepted. 225+ patents is strongest IP portfolio among small companies.', deepResearchPrompt:'Research CII Industrial IP Awards 2026. Application process, deadline, categories, whether company with primarily US patents qualifies via Indian entity, past winners.', notes:'Apply through INSPIN. 225+ patents dominates this category.', url:'https://www.cii.in', entity:'INSPIN' },
  { id:'nai-member', category:'awards', name:'NAI Senior Member / Fellow (National Academy of Inventors)', amount:'Prestigious designation', status:'todo', priority:11, warmIntro:false, deadline:'Rolling', action:'Secure adjunct or research affiliation with a NAI Member Institution (University of Michigan, NC State, or similar). Then self-nominate at academyofinventors.org. 225+ patents is a slam dunk.', deepResearchPrompt:'Research NAI Senior Member and Fellow designation 2026. What institutional affiliation is required and how formal it must be, whether NC State collaboration with Krishna Namburi satisfies the requirement, application process, what the designation unlocks for future grants and nominations.', notes:'NC State collaboration may satisfy institutional affiliation. 225+ patents = automatic Senior Member. Fellow requires more.', url:'https://academyofinventors.org', entity:'Prerit individually' },
  { id:'edison-awards', category:'awards', name:'Edison Awards', amount:'Medal + marketing visibility', status:'todo', priority:12, warmIntro:false, deadline:'Nomination by Nov 2026 for 2027 awards', action:'Select a specific hardware or software product launched under II LLC between Jan 2024 and Jan 2026. Pay nomination fee ($1,250+). Submit at edisonawards.com.', deepResearchPrompt:'Research Edison Awards 2026. Nomination fee details, categories, judging criteria, what marketing value the award actually provides, past winners in motor controls or autonomous systems.', notes:'Pay-to-play model. Nomination fee required. High marketing visibility and investor credibility.', url:'https://edisonawards.com', entity:'II LLC' },

  // ── PRIZES & COMPETITIONS
  { id:'hubspot-aIdea', category:'competitions', name:'HubSpot Next Big AIdea', amount:'$50K cash + $25K AWS', status:'todo', priority:1, warmIntro:false, deadline:'July 25, 2026', action:'60-second phone video. UDC-based autonomous AI control system is the angle. Submit at hubspot.com/nextbigaidea. Do this the week NSF pitch is submitted.', deepResearchPrompt:'Research HubSpot Next Big AIdea 2026. Submission portal, video format, judging criteria, past winner profiles, whether deep tech hardware-adjacent AI is competitive vs SaaS.', notes:'Fastest $75K play in this tracker. Phone video only. Deadline July 25.', url:'https://www.hubspot.com/nextbigaidea', entity:'II LLC' },
  { id:'global-energy-prize', category:'competitions', name:'Global Energy Prize', amount:'~$500K (split among 2-3)', status:'todo', priority:2, warmIntro:false, deadline:'~April 2027 (annual) — April 2026 passed', action:'Urgently identify a highly credentialed IEEE or academic peer to submit a formal nomination before the next annual deadline (~April 2027). Self-nomination strictly disqualifies. Narrative: electric machines and grid intelligence.', deepResearchPrompt:'Research Global Energy Prize 2027 cycle. Exact nomination deadline, who can nominate, electronic portal process, what evidence of global impact is required, recent winners and their profiles.', notes:'Self-nomination strictly disqualifies. Need peer or IEEE colleague to nominate. Electric power and grid intelligence is the core narrative.', url:'https://globalenergyprize.org', entity:'Prerit individually' },
  { id:'army-xtech', category:'competitions', name:'Army xTech Competition', amount:'$25K–$275K', status:'todo', priority:3, warmIntro:false, deadline:'Recurring — check arl.army.mil/xtech now', action:'Find currently open xTech track. Robotics, AI, power, autonomous systems all fit. White paper only for Phase 1.', deepResearchPrompt:'Research Army xTech competitions open June 2026. Open tracks, prize amounts per phase, Phase 1 format, judging criteria, solo founder competitiveness.', notes:'$25K-$275K across phases. No prototype for Phase 1.', url:'https://www.arl.army.mil/about/small-business-programs/xtech/', entity:'II LLC' },
  { id:'doe-american-made', category:'competitions', name:'DOE American-Made Prizes', amount:'$50K–$500K per phase', status:'todo', priority:4, warmIntro:false, deadline:'Multiple open now — check americanmadechallenges.org', action:'Go to americanmadechallenges.org. Find open competitions in manufacturing, energy, motors, propulsion. Submit to nearest deadline.', deepResearchPrompt:'Research DOE American-Made Challenges open June 2026. All currently open especially in electric motors, rare-earth-free materials, advanced manufacturing, space propulsion. Prize amounts, deadlines, eligibility.', notes:'Multiple run simultaneously. BESM, USM, PR020 all fit.', url:'https://americanmadechallenges.org', entity:'II LLC' },
  { id:'nasa-centennial', category:'competitions', name:'NASA Centennial Challenges', amount:'$50K–$300K+', status:'todo', priority:5, warmIntro:false, deadline:'Multiple active — check nasa.gov/prize-challenges', action:'Check nasa.gov/prize-challenges. NASA explicitly welcomes individual inventors. Space propulsion, active structures, orbital systems fit MSS.', deepResearchPrompt:'Research NASA Centennial Challenges open June 2026. All open challenges, prize amounts, individual and solo LLC eligibility, timeline to award.', notes:'NASA explicitly targets independent inventors. MSS orbital reentry and active structures are direct fits.', url:'https://www.nasa.gov/prize-challenges', entity:'MSS' },
  { id:'xprize', category:'competitions', name:'XPRIZE (Various)', amount:'$5M–$100M', status:'todo', priority:6, warmIntro:false, deadline:'Varies — check xprize.org/competitions', action:'Check xprize.org for currently open competitions in energy, AI, or space. Requires team or consortium and private co-investment for entry. High effort but massive payoff.', deepResearchPrompt:'Research currently open XPRIZE competitions 2026. Which prizes are open, which allow small LLC teams without significant private capital, what the entry requirements are, whether a simulation-only team can advance early rounds.', notes:'Requires consortium building. High effort. Wildfire, quantum, or space prize may fit. Long shot but massive prize pool.', url:'https://www.xprize.org/competitions', entity:'MSS or II LLC' },
  { id:'techstars-space', category:'competitions', name:'Techstars Space Accelerator', amount:'$120K + in-kind', status:'todo', priority:7, warmIntro:false, deadline:'Cohort-based — apply now', action:'Apply at techstars.com/space. MSS orbital maneuver and propulsion thesis.', deepResearchPrompt:'Research Techstars Space Accelerator 2026. Next cohort deadline, DoD and Space Force intro opportunities, alumni outcomes, acceptance rate.', notes:'Strong DoD intro network post-program.', url:'https://www.techstars.com/accelerators/space', entity:'MSS' },
  { id:'hyperspace', category:'competitions', name:'Hyperspace Challenge', amount:'Contract potential', status:'todo', priority:8, warmIntro:false, deadline:'Check hyperspacechallenge.com', action:'Submit under MSS for orbital maneuver, active structures, or Space Force mission matching.', deepResearchPrompt:'Research Hyperspace Challenge 2026. Open challenges, Space Force/AFRL problem sets, typical contract award size, solo founder competitiveness.', notes:'Government-backed. Space Force and AFRL problem sets.', url:'https://hyperspacechallenge.com', entity:'MSS' },

  // ── INDIA TRACK
  { id:'iete-pr001', category:'india', name:'IETE National Engineering Excellence Initiative (PR001)', amount:'~₹40 crore over 3 years', status:'inprogress', priority:1, warmIntro:false, deadline:'Financial documentation required — active TONIGHT', action:'Pre-approval received ~May 29, 2026. Financial documentation and India travel are next steps. THIS IS THE PRIORITY TONIGHT.', deepResearchPrompt:'Research IETE India engineering initiative grant structure 2026. Financial documentation required for pre-approved government initiatives at ₹40 crore scale, milestone and disbursement structure for 3-year programs.', notes:'LARGEST SINGLE OPPORTUNITY IN THIS TRACKER. Pre-approved. Financial docs are the blocker.', url:'https://www.iete.org', entity:'INSPIN' },
  { id:'idex', category:'india', name:'iDEX Open Challenge (India Defense)', amount:'Up to ₹1.5 crore (~$180K)', status:'inprogress', priority:2, warmIntro:false, deadline:'Rolling — check idex.gov.in', action:'Submit via idex.gov.in. QESM (rare-earth-free motor) for UAV/defense propulsion. Exoskeleton for military. 4 PDFs under 200KB each. No prototype required.', deepResearchPrompt:'Research iDEX Open Challenge current cycle 2026. Open problem statements, matching contribution rules (50% cash, founder salary counts), SPARK grant terms.', notes:'QESM for UAV propulsion hits autonomous vehicles, eVTOL, naval. Multiple proposals under PR013. Ashutosh Lal as ops lead.', url:'https://idex.gov.in', entity:'INSPIN' },
  { id:'nidhi-prayas', category:'india', name:'NIDHI-PRAYAS (DST India)', amount:'Up to ₹10 lakhs (~$12K)', status:'todo', priority:3, warmIntro:false, deadline:'Rolling via DST-approved incubators', action:'Apply through SINE at IIT Bombay or IIT Delhi incubator. Concept-to-prototype grant.', deepResearchPrompt:'Research NIDHI-PRAYAS DST India 2026. Approved PRAYAS centers, application process, prototype support, timeline, NRI-held company eligibility.', notes:'Fastest-turnaround Indian funding for concept-stage work.', url:'https://dst.gov.in/nidhi', entity:'INSPIN' },
  { id:'infosys-india', category:'india', name:'Infosys Prize — Engineering & CS (India)', amount:'$100K USD', status:'todo', priority:4, warmIntro:false, deadline:'URGENT — nomination spring 2026, age cutoff 40', action:'Urgently cultivate relationships with Infosys Science Foundation Nomination Council members. Self-nomination forbidden. You are 36 — 4 years left. Contact IIT professors and IEEE India leadership as nominators.', deepResearchPrompt:'Research Infosys Prize Engineering and CS 2026. Nomination Council member list, how to reach them, recent winners, exact age cutoff date, nomination submission deadline and process.', notes:'URGENT. Age closes permanently at 40. Indian citizenship qualifies. Autonomous systems and diagnostics are the angle.', url:'https://www.infosysprize.org', entity:'Prerit individually' },
  { id:'agnii', category:'india', name:'AGNIi Platform (India, Invest India)', amount:'Non-cash — market access + procurement', status:'todo', priority:5, warmIntro:false, deadline:'Rolling', action:'Register INSPIN validated technologies (thermal management algorithms, sensorless control modules) on the AGNIi portal at investindia.gov.in/agnii. Attracts defense contractor and OEM pilot contracts.', deepResearchPrompt:'Research AGNIi platform Invest India 2026. How to register technology, what procurement access it provides, which defense contractors and automotive OEMs participate, timeline from registration to first engagement.', notes:'Non-cash but strategic multiplier. Opens Indian defense contractor and automotive OEM doors.', url:'https://www.investindia.gov.in/agnii', entity:'INSPIN' },
  { id:'usistef', category:'india', name:'USISTEF (US-India Science and Technology Fund)', amount:'~$500K', status:'todo', priority:6, warmIntro:false, deadline:'Periodic — check usistef.org', action:'Apply at usistef.org. II LLC (US) + INSPIN (India) is the perfect joint entity structure. Rare-earth-free motors for energy security is the angle.', deepResearchPrompt:'Research USISTEF 2026. Next solicitation opening, joint team requirements, eligible technology areas, II LLC + INSPIN bilateral qualification.', notes:'II LLC + INSPIN is purpose-built for this bilateral program.', url:'https://www.usistef.org', entity:'II LLC + INSPIN' },
  { id:'abdul-kalam', category:'india', name:'Abdul Kalam Technology Innovation Fellowship (INAE-SERB)', amount:'₹25K/mo + ₹15L/yr research', status:'todo', priority:7, warmIntro:false, deadline:'~June 2026 — check serb.gov.in', action:'Requires adjunct appointment at IIT or NIT first. Contact IIT Delhi or IIT Bombay EE for visiting faculty role, then apply at serb.gov.in.', deepResearchPrompt:'Research Abdul Kalam Fellowship INAE-SERB 2026. Exact deadline, adjunct requirement formality, NRI with US PR eligibility, what the fellowship funds.', notes:'Most aligned India fellowship. IIT adjunct appointment is the prerequisite.', url:'https://serb.gov.in', entity:'Prerit via INSPIN' },

  // ── GLOBAL PRIZES
  { id:'global-energy-prize-main', category:'global', name:'Global Energy Prize', amount:'~$500K (split 2-3 winners)', status:'todo', priority:1, warmIntro:false, deadline:'Annual — next cycle April 2027', action:'Identify a peer or IEEE colleague to submit formal nomination. Self-nomination strictly disqualifies. Narrative: electric machines, grid intelligence, rare-earth-free propulsion. Start building this now.', deepResearchPrompt:'Research Global Energy Prize 2027 cycle. Who can nominate, electronic portal, evidence of global impact required, recent winners profiles, evaluation criteria.', notes:'Requires external nomination. Electric power and grid intelligence narrative. Start cultivation now for 2027.', url:'https://globalenergyprize.org', entity:'Prerit individually' },

  // ── CANADA TRACK
  { id:'nrc-irap', category:'canada', name:'NRC-IRAP Canada', amount:'Up to CAD $500K', status:'todo', priority:1, warmIntro:false, deadline:'Rolling — requires Canadian incorporation first', action:'Incorporate a Canadian entity via Ownr.co (1 day, ~$500). Then contact NRC Industrial Technology Advisor (ITA). Apply at nrc.canada.ca/irap. Clean Tech stream = BESM.', deepResearchPrompt:'Research NRC-IRAP Canada 2026. Canadian incorporation requirements for US-based PR holder, ITA role, whether solo founder with no Canadian employees qualifies, typical award timeline, Clean Tech stream details.', notes:'Canadian PR since 2021. One-day incorporation unlocks this. Reimbursement model: up to 80% of technical salary, 50% of subcontractor costs.', url:'https://nrc.canada.ca/en/support-technology-innovation/nrc-industrial-research-assistance-program', entity:'New Canadian entity (1 day to incorporate)' },
  { id:'nrc-killam', category:'canada', name:'Killam NRC / Paul Corkum Fellowship', amount:'R&D funding + NRC lab access', status:'todo', priority:2, warmIntro:false, deadline:'Check nrc.canada.ca — was Jun 9, 2026', action:'Check if current cycle is still open. Need NRC co-PI. Open to non-Canadians. Clean energy, AI, manufacturing focus.', deepResearchPrompt:'Research NRC Killam / Paul Corkum Fellowship 2026. Whether current cycle is still accepting, co-PI requirement details, lab access provided, Canadian PR holder eligibility, priority technology areas.', notes:'Open to international scholars. Canadian PR strengthens eligibility.', url:'https://nrc.canada.ca', entity:'Prerit individually' },

  // ── EXPERT WITNESS
  { id:'round-table-group', category:'expertwitness', name:'Round Table Group', amount:'$400–$800/hr', status:'todo', priority:1, warmIntro:false, deadline:'Apply TONIGHT — fastest cash in this tracker', action:'Apply at roundtablegroup.com. 10 minutes. Profile: motor controls, EPS, perception, autonomy patents, IP litigation, power electronics. 225+ patents, 15 years Nexteer.', deepResearchPrompt:'Research Round Table Group 2026. Application process, onboarding time, rate range for 225-patent motor controls profile, case assignment, non-compete clauses.', notes:'No deck, no pitch, no dilution. 10 hours = $5K-8K cash. Apply tonight.', url:'https://roundtablegroup.com', entity:'II LLC' },
  { id:'expert-institute', category:'expertwitness', name:'Expert Institute', amount:'$400–$800/hr', status:'todo', priority:2, warmIntro:false, deadline:'Apply TONIGHT — same night as Round Table', action:'Apply at expertinstitute.com. Motor controls, IP litigation, autonomy, power electronics.', deepResearchPrompt:'Research Expert Institute 2026. Application, rate ranges, most common EE and IP case types, case matching, non-compete clauses.', notes:'Two bites at the same apple. Apply both tonight.', url:'https://www.expertinstitute.com', entity:'II LLC' },
  { id:'tasa', category:'expertwitness', name:'TASA (Technical Advisory Service for Attorneys)', amount:'$300–$600/hr', status:'todo', priority:3, warmIntro:false, deadline:'Apply now', action:'Apply at tasanet.com. Motor controls, automotive, robotics, power electronics.', deepResearchPrompt:'Research TASA expert witness 2026. Application, rate ranges, EE and automotive case types, case matching, exclusivity requirements.', notes:'One of the largest expert witness networks. More case volume than boutique networks.', url:'https://www.tasanet.com', entity:'II LLC' },

  // ── EXPERT NETWORKS
  { id:'glg', category:'consulting', name:'GLG / AlphaSights / Dialectica', amount:'$300–$600/hr', status:'active', priority:1, warmIntro:false, deadline:'Ongoing — increase frequency NOW', action:'Accept more project matches. High-demand topics: EV motors, humanoid robotics, transfer cases, LiDAR, autonomy, rare-earth supply chain, space propulsion. Target 5-10 calls/month.', deepResearchPrompt:'Research GLG, AlphaSights, Dialectica rates 2026. Highest-demand topics for EE and autonomy. Realistic monthly income at 5-10 calls/month. New high-value niches from humanoid robotics boom.', notes:'Already active. Kirk Cox for transfer case thread. Humanoid robotics is booming demand topic.', url:'https://glginsights.com', entity:'II LLC' },
  { id:'alien-tech-transfer', category:'consulting', name:'Alien Technology Transfer (SBIR Consultant)', amount:'Success fee only — zero upfront', status:'todo', priority:2, warmIntro:false, deadline:'Contact before next NSF/DOE submission', action:'Contact Alien Technology Transfer (Austin TX) for free Funding Opportunity Assessment. Pure success fee. Strong for NSF, DOE, and EIC Accelerator (Europe).', deepResearchPrompt:'Research Alien Technology Transfer SBIR consulting 2026. Client reviews, success rate, agencies won, experience with rare-earth-free motor or aerospace propulsion topics, success fee percentage.', notes:'Zero risk engagement. Vetted March 2026. Also covers EIC Accelerator for European funding.', url:'https://www.alientechnologytransfer.com', entity:'II LLC or MSS' }

];

export const DEEP_RESEARCH_MASTER = `# Master Deep Research Prompt: Complete Funding Landscape 2026

Conduct an exhaustive research sweep of ALL funding pathways for the following founder as of June 2026:

FOUNDER: Prerit Pramod
- US PR (EB-1A 2024), Indian citizen, Canadian PR (2021), based Redmond WA, born July 9 1989 (age 36)
- 225+ global patents (~150 granted), 40+ publications, ~900 citations
- IEEE Senior Member, IEEE IAS Andrew W. Smith Young Member Award 2024
- Nexteer Automotive Platinum IP Hall of Fame (youngest/fastest ever), Melvin Wilcox Award
- Technologies generated ~$7B lifetime revenues
- MS EE Systems/Control, University of Michigan 2012; BE EE, Delhi College of Engineering 2010

ENTITIES:
- Inspired Innovation LLC (US, Redmond WA) — multi-vertical deep tech, solo operator
- Multiscale Space Systems LLC (US) — space propulsion + orbital reentry, co-founded with Shardul Singh Panwar
- INSPIN Private Limited (India) — defense and manufacturing focus
- Canadian entity: none yet (PR since 2021, one-day incorporation possible)

TECHNICAL AREAS:
UDC/UDCF, USM, BESM/QESM (rare-earth-free synchronous motors), visual perception, orbital reentry vehicles, aerospace active structures, autonomous military vehicles, humanoid actuators, EPS/steer-by-wire, power electronics, LiDAR, UTEI (energy intelligence), exoskeletons

SEARCH EVERYTHING:
1. Pre-seed VCs: A&D, deep tech, space, autonomy, cold pitches accepted
2. Federal SBIR/STTR: NSF, DOE (VTO+AMMTO), DoD all branches (Army, Navy, AF, DARPA, Space Force, MDA, SOCOM), NASA, NIST, DOT, DHS, NIH (for exoskeleton)
3. DARPA BAAs all offices, DIU CSOs, AFRL ARAs, AFWERX
4. ARPA-E OPEN and focused programs, ARPA-H
5. DOE Small Business Vouchers, national lab partnerships
6. Prize competitions: DOE American-Made, Army xTech, NASA Centennial, Navy challenges, XPRIZE, HubSpot AIdea, Global Energy Prize
7. Fellowships: Activate, Innovation Crossroads (ORNL), Chain Reaction (Argonne), West Gate (NREL), Breakthrough Energy
8. Nomination awards: MacArthur, Lemelson-MIT, Earthshot, IEEE Nikola Tesla, Nagamori, Infosys Prize, WIPO Global, Zayed Prize, NAI Fellow, Edison Awards
9. India: iDEX all tracks, NIDHI-PRAYAS, DST SERB programs, Abdul Kalam Fellowship, USISTEF, Infosys Prize, AGNIi, IETE, CII IP Awards
10. Canada: NRC-IRAP, NRC Killam, SDTC, BDC programs
11. Expert witness: Round Table Group, Expert Institute, TASA, Courtroom Insight, others
12. Expert networks: GLG, AlphaSights, Dialectica, Guidepoint, Third Bridge, Tegus — highest-paying 2026 topics
13. Corporate cloud credits: NVIDIA Inception, AWS Activate, Google for Startups, Microsoft for Startups, Oracle for Startups
14. SBIR consulting firms: success-fee only, no upfront
15. European: EIC Accelerator, Horizon Europe, ESA BIC — via Alien Tech Transfer or direct
16. Japan: Nagamori Foundation, JST programs
17. Global multilateral: WIPO, UN programs, World Bank innovation

For each opportunity output:
- Name, sponsor, amount, deadline, entity vehicle (which of Prerit's entities)
- Eligibility gatechecks: citizenship, PR, incorporation, age, PhD required?
- Submission method: self-nomination, peer nomination, application portal
- Why this specific founder wins (one sentence)
- Priority score 1-10 based on: fit, amount, friction, timeline to money

Rank final output by: (1) fastest to cash, (2) highest amount, (3) lowest friction.`;
